apiVersion: v2
name: seafile
description: A Helm chart for Seafile Server
type: application
version: 0.4.4
appVersion: 8.0.5
home: https://github.com/300481/seafile-server
description: Seafile Server, Reliable and Performant File Sync and Share Solution on Kubernetes
keywords:
  - cloud
  - file
  - share
  - sync
sources:
  - https://github.com/300481/seafile-server
maintainers:
  - name: "300481"
engine: gotpl
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/changes: |
    - Update to Seafile v8.0.5 latest container build
  artifacthub.io/images: |
    - name: Seafile
      image: 300481/seafile:8.0.5-20210514
    - name: Memcached
      image: memcached:1.6.9-alpine
    - name: MariaDB
      image: mariadb:10.5
  artifacthub.io/maintainers: |
    - name: 300481
      email: 300481@300481.de
