apiVersion: v2
name: seafile
description: A Helm chart for Seafile Server
type: application
version: 1.0.0
appVersion: 11.0.2
icon: https://www.seafile.com/media/img/seafile-logo.png
home: https://github.com/300481/seafile-server
description: Seafile Server, Reliable and Performant File Sync and Share Solution on Kubernetes
keywords:
  - cloud
  - file
  - share
  - sync
sources:
  - https://github.com/300481/seafile-server
maintainers:
  - name: "300481"
engine: gotpl
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/changes: |
    - add option to disable subchart memcached
  artifacthub.io/images: |
    - name: Seafile
      image: seafileltd/seafile-mc:11.0.2
  artifacthub.io/maintainers: |
    - name: 300481
      email: 300481@300481.de
dependencies:
  - name: mariadb
    version: 14.1.2
    repository: https://charts.bitnami.com/bitnami
  - name: memcached
    version: 6.7.0
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled