apiVersion: v2
name: seafile
type: application
version: 0.12.0
appVersion: 11.0.3
icon: https://www.seafile.com/media/img/seafile-logo.png
home: https://github.com/300481/seafile-server
description: Seafile Server, Reliable and Performant File Sync and Share Solution on Kubernetes
keywords:
  - cloud
  - file
  - share
  - sync
sources:
  - https://github.com/300481/seafile-server
maintainers:
  - name: "300481"
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/changes: |
    - update README.md
  artifacthub.io/images: |
    - name: Seafile
      image: docker.io/seafileltd/seafile-mc:11.0.3
  artifacthub.io/maintainers: |
    - name: 300481
      email: 300481@300481.de
dependencies:
  - name: mariadb
    version: 16.4.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
