# Default values for seafile-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterDomain: cluster.local

# see Bitnami MariaDB Chart Values
# https://artifacthub.io/packages/helm/bitnami/mariadb
# mariadb:
  # auth:
  #   rootPassword: generated-pw-needed-for-chart-upgrade
  # primary:
  #   extraVolumes:
  #   - name: mnt-data-db
  #     persistentVolumeClaim:
  #       claimName: mnt-data-db
  #   extraVolumeMounts:
  #   - mountPath: "/mnt/data/db"
  #     name: mnt-data-db
  #   livenessProbe:
  #     enabled: false
  #   readinessProbe:
  #     enabled: false

# see Bitnami Memcached Chart Values
# https://artifacthub.io/packages/helm/bitnami/memcached
memcached:
  enabled: true
  serviceFqdn: memcached

mariadb:
  enabled: true

seafile:
  image: docker.io/300481/seafile:8.0.85-20231130
  pause: false
  persistence:
    size: 10Gi
    storageClassName: {}
  database:
    hostname: {}
    rootPasswordSecret:
      name: {}
      key: {}
  environment:
  - name: TIME_ZONE
    value: "Etc/UTC"
  - name: SEAFILE_ADMIN_EMAIL
    value: "seafileadmin@example.com"
  - name: SEAFILE_ADMIN_PASSWORD
    value: "secretpassword"
    # !!! update the service and seahub URL to https in the Web-UI !!!
  - name: SEAFILE_SERVER_HOSTNAME
    value: "seafile.example.com"
  # extraVolumes:
  # - name: mnt-data-seafile
  #   persistentVolumeClaim:
  #     claimName: mnt-data-seafile
  # extraVolumeMounts:
  # - mountPath: "/mnt/data/seafile"
  #   name: mnt-data-seafile

ingress:
  annotations:
    # use NGINX Ingress Controller
    kubernetes.io/ingress.class: "nginx"
    # use Cert-Manager for LetsEncrypt Certificates
    # cert-manager.io/issuer: "letsencrypt-prod"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: "seafile.example.com"
# tls:
#   host: "seafile.example.com"
#   secretName: seafile-tls
