# see Bitnami MariaDB Chart Values
# https://artifacthub.io/packages/helm/bitnami/mariadb
# mariadb:
  # auth:
  #   rootPassword: generated-pw-needed-for-chart-upgrade
  # primary:
  #   extraVolumes:
  #   - name: mnt-data-db
  #     persistentVolumeClaim:
  #       claimName: mnt-data-db
  #   extraVolumeMounts:
  #   - mountPath: "/mnt/data/db"
  #     name: mnt-data-db
  #   livenessProbe:
  #     enabled: false
  #   readinessProbe:
  #     enabled: false

# see Bitnami Memcached Chart Values
# https://artifacthub.io/packages/helm/bitnami/memcached

clusterDomain: cluster.local

memcached:
  enabled: true
  serviceFqdn: memcached

imagePullSecret: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

seafile:
  replicas: 1
  image:
    repository: seafileltd/seafile-mc
    tag: ""
    pullPolicy: IfNotPresent
  existingSecret: ""
  auth:
    adminMail: ""
    adminPassword: ""
  persistence:
    size: 10Gi
  env:
    - name: TIME_ZONE
      value: "Etc/UTC"
  # extraVolumes:
  # - name: mnt-data-seafile
  #   persistentVolumeClaim:
  #     claimName: mnt-data-seafile
  # extraVolumeMounts:
  # - mountPath: "/mnt/data/seafile"
  #   name: mnt-data-seafile
  resources: {}
  probes:
    # livenessProbe:
    #   httpGet:
    #     path: /
    #     port: http
    #   failureThreshold: 3
    #   timeoutSeconds: 40
    #   periodSeconds: 20
    #   initialDelaySeconds: 40
    # readinessProbe:
    #   httpGet:
    #     path: /
    #     port: http
    #   failureThreshold: 3
    #   timeoutSeconds: 40
    #   periodSeconds: 20
    #   initialDelaySeconds: 40
    startupProbe:
      tcpSocket:
        port: http
      failureThreshold: 60
      timeoutSeconds: 20
      periodSeconds: 5
      initialDelaySeconds: 60

ingress:
  className: ""
  annotations:
    # use Cert-Manager for LetsEncrypt Certificates
    # cert-manager.io/issuer: "letsencrypt-prod"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # !!! update the service and seahub URL to https in the Web-UI !!!
  host: "seafile.example.com"
# tls:
#   host: "seafile.example.com"
#   secretName: seafile-tls


podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - SETUID
      - SETGID
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}

tolerations: []

affinity: {}
