# Default values for seafile-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

seafile:
  image: docker.io/seafileltd/seafile-mc:9.0.5
  pause: false
  persistence:
    size: 10Gi
    storageClassName: {}
    existingClaim: {}
  database:
    hostname: {}
    rootPasswordSecret:
      name: {}
      key: {}
  environment:
  - name: TIME_ZONE
    value: "Etc/UTC"
  - name: SEAFILE_ADMIN_EMAIL
    value: "seafileadmin@example.com"
  - name: SEAFILE_ADMIN_PASSWORD
    value: "secretpassword"
    # !!! update the service and seahub URL to https in the Web-UI !!!
  - name: SEAFILE_SERVER_HOSTNAME
    value: "seafile.example.com"

ingress:
  annotations:
    # use NGINX Ingress Controller
    kubernetes.io/ingress.class: "nginx"
    # use Cert-Manager for LetsEncrypt Certificates
    # cert-manager.io/issuer: "letsencrypt-prod"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: "seafile.example.com"
# tls:
#   host: "seafile.example.com"
#   secretName: seafile-tls
