{{- if .Values.persistence.volumeClaim -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seafile-db
spec:
  storageClassName: {{ .Values.persistence.volumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.volumeClaim.size.db }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seafile-data
spec:
  storageClassName: {{ .Values.persistence.volumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.volumeClaim.size.data }}
{{- end }}