---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.fullname" . }}
  labels: {{ include "seafile.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "seafile.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}