{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: seafile
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.tls.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.tls.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: seafile
          servicePort: 80
{{- end }}
