{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "seafile.fullname" . }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  admin-username: {{ template "seafile.adminMail" . }}
  admin-password: {{ template "seafile.adminPassword" . }}
{{- end }}
