---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.fullname" . }}
  labels:
{{ include "seafile.labels" . | indent 4 }}
spec:
  type: ClusterIP
{{- if (eq .Values.kind "StatefulSet") }}
  ClusterIP: "None"
{{- end }}
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "seafile.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
{{ include "seafile.labels" . | indent 4 }}
spec:
  type: ClusterIP
{{- if (eq .Values.kind "StatefulSet") }}
  ClusterIP: "None"
{{- end }}
  ports:
  - port: 11211
    targetPort: memcached
    protocol: TCP
    name: memcached
  selector:
    app.kubernetes.io/name: {{ include "seafile.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
